apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: todo-namespace
spec:
  type: LoadBalancer
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000