name: Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: kube
  GKE_ZONE: asia-southeast1-a
  DEPLOYMENT_NAME: todo-app
  IMAGE: todo-frontend-app
  NAMESPACE: todo-namespace

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1

    # Configure Docker to use the gcloud command-line tool as a credential helper for Artifact Registry
    - name: Configure Docker
      run: |-
        gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE Credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "us-central1-docker.pkg.dev/$PROJECT_ID/todo-app/todo-frontend-app:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Artifact Registry
    - name: Push
      run: |-
        docker push "us-central1-docker.pkg.dev/$PROJECT_ID/todo-app/todo-frontend-app:$GITHUB_SHA"

    # Update the image tag in deployment.yaml
    - name: Update deployment image
      run: |-
        sed -i "s|us-central1-docker.pkg.dev/cloud-run-412614/todo-app/todo-frontend-app:latest|us-central1-docker.pkg.dev/$PROJECT_ID/todo-app/todo-frontend-app:$GITHUB_SHA|g" k8s/deployment.yaml

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f k8s/deployment.yaml -n $NAMESPACE
        kubectl apply -f k8s/service.yaml -n $NAMESPACE
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
        
    # Get service information
    - name: Get Service URL
      run: |-
        echo "Waiting for LoadBalancer external IP..."
        sleep 30
        kubectl get services todo-app -o wide
        echo "Your Todo app should be accessible via the LoadBalancer external IP on port 80" 