name: Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: kube
  GKE_ZONE: asia-southeast1-a
  DEPLOYMENT_NAME: todo-app
  IMAGE: todo-frontend-app
  NAMESPACE: todo-namespace

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Get GKE Credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

    - name: Build
      run: |-
        docker build \
          --tag "us-central1-docker.pkg.dev/$PROJECT_ID/todo-app/todo-frontend-app:$GITHUB_SHA" \
          --tag "us-central1-docker.pkg.dev/$PROJECT_ID/todo-app/todo-frontend-app:latest" \
          .

    - name: Push
      run: |-
        docker push "us-central1-docker.pkg.dev/$PROJECT_ID/todo-app/todo-frontend-app:$GITHUB_SHA"
        docker push "us-central1-docker.pkg.dev/$PROJECT_ID/todo-app/todo-frontend-app:latest"

    - name: Deploy
      run: |-
        # Update deployment with new image
        sed -i "s|us-central1-docker.pkg.dev/\${PROJECT_ID}/todo-app/todo-frontend-app:latest|us-central1-docker.pkg.dev/$PROJECT_ID/todo-app/todo-frontend-app:$GITHUB_SHA|g" k8s/deployment.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f k8s/deployment.yaml -n $NAMESPACE
        kubectl apply -f k8s/service.yaml -n $NAMESPACE
        
        # Wait for deployment to complete
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE --timeout=300s
        
    - name: Get Service URL
      run: |-
        echo "Waiting for LoadBalancer external IP..."
        sleep 30
        kubectl get services todo-app -n $NAMESPACE -o wide
        echo "Your Todo app should be accessible via the LoadBalancer external IP on port 80" 